
import './globals.css'
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import {NextIntlClientProvider , hasLocale} from 'next-intl'
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import {getMessages} from 'next-intl/server'
import type {ReactNode} from 'react'
import { SupabaseProvider } from '@/components/providers/SupabaseProvider';

type LayoutProps = {
  children: ReactNode
  // ⬇️ params est maintenant une Promise
  params: Promise<{locale: string}>
}

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-ui-primary',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children, params}: LayoutProps) {
  const {locale} = await params           // ⬅️ on attend params

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages({locale})
  return (
    <html lang={locale}>
      <body className={`${quicksand.variable} antialiased`}>
        <NextIntlClientProvider 
          // messages={messages} locale={locale}
          >
            <SupabaseProvider>
              {children}
            </SupabaseProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
